server:
  port: 8002

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: desktop-2vav0fh
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://desktop-2vav0fh:8002/eureka/
  server:
    enable-self-preservation: false

endpoints:
  shutdown:
    enabled: true