server:
  port: 58328

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 10.1.7.82
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:58328/eureka/
  server:
    enable-self-preservation: false
management:
  endpoint:
    shutdown:
      enabled: true
