server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 10.40.17.44
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.40.17.44:8761/eureka/
  server:
    enable-self-preservation: false

endpoints:
  shutdown:
    enabled: true