column:
  xugu:
    integer: integer
    int: int
    pls_integer: integer
    binary_integer: integer
    bigint: bigint
    longint: bigint
    long: bigint
    float: float
    binary_float: float
    double: double
    binary_double: double
    real: double
    tinyint: tinyint
    smallint: smallint
    short: smallint
    numeric: numeric
    decimal: numeric
    char: char
    nchar: nchar
    varchar: varchar
    nvarchar: varchar
    nvarchar2: varchar
    varchar2: varchar
    clob: clob
    text: text
    nclob: nclob
    guid: guid
    boolean: boolean
    bool: bool
    blob: blob
    binary: binary
    raw: binary
    rowversion: rowversion
    timestamp: timestamp
    date: date
    datetime: datetime
    time: time
    interval: interval
  gbase8a:
    tinyint: tinyint
    smallint: smallint
    int: int
    bigint: bigint
    float: float
    double: double
    decimal: decimal
    numeric: numeric
    char: char
    varchar: varchar
    text: text
    blob: blob
    longblob: longblob
    date: date
    datetime: datetime
    time: time
    timestamp: timestamp
  cassandra:
    bigint: bigint
    blob: blob
    boolean: boolean
    counter: counter
    date: date
    decimal: decimal
    double: double
    float: float
    inet: inet
    int: int
    smallint: smallint
    text: text
    time: time
    timestamp: timestamp
    datetime: timestamp
    tinyint: tinyint
    uuid: uuid
    varchar: varchar
    varint: varint
    map: map
    set: set
    list: list
  postgresql:
    smallint: smallint
    integer: integer
    bigint: bigint
    decimal: decimal
    numeric: numeric
    real: real
    double precision: double precision
    smallserial: smallserial
    serial: serial
    bigserial: bigserial
    money : money
    character varying: character varying
    varchar: varchar
    character: character
    char: char
    text: text
    timestamp: timestamp
    date: date
    time: time
    array_to_json: array_to_json
    row_to_json: row_to_json
    bytea: bytea
dclsql:
  xugu:
    createuser: "CREATE USER % IDENTIFIED BY '%'"
    updateaccount: "ALTER USER % IDENTIFIED BY '%'"
    deleteuser: "DROP USER %"
    lockuser: "ALTER USER % ACCOUNT LOCK"
    usernum: "SELECT COUNT(*) FROM DBA_USERS WHERE USER_NAME='%'"
    schemasnum: "SELECT COUNT(*) FROM DBA_SCHEMAS WHERE SCHEMA_NAME = '%'"
    addpermissions: "GRANT % ON %.% To %"
    deletepermissions: "REVOKE % ON %.% FROM %"
    createschemas: "CREATE SCHEMA % AUTHORIZATION %"
    dropschemas: "DROP SCHEMA %"
    author: "GRANT % ANY TABLE IN SCHEMA % TO %"
  gbase8a:
    createuser: "CREATE USER '%'@'%' IDENTIFIED BY '%'"
    updateaccount: "ALTER USER % IDENTIFIED BY '%'"
    deleteuser: "DROP USER %"
    deleteipuser: "DROP USER '%'@'%'"
    lockuser: "ALTER USER % ACCOUNT LOCK"
    usernum: "SELECT COUNT(*) FROM GBASE.USER WHERE USER='%'"
    schemasnum: "SELECT COUNT(*) FROM DBA_SCHEMAS WHERE SCHEMA_NAME = '%'"
    addpermissions: "GRANT % ON %.% To %"
    deletepermissions: "REVOKE % ON %.% FROM %"
    createschemas: "CREATE SCHEMA % AUTHORIZATION %"
    dropschemas: "DROP SCHEMA %"
    author: "GRANT % ANY TABLE IN SCHEMA % TO %"
databasename:
  xugu: xugu
  gbase8a: gbase8a
  cassandra: cassandra
  postgresql: postgresql