column:
  xugu:
    integer: integer
    int: int
    pls_integer: integer
    binary_integer: integer
    bigint: bigint
    longint: bigint
    long: bigint
    float: float
    binary_float: float
    double: double
    binary_double: double
    real: double
    tinyint: tinyint
    smallint: smallint
    short: smallint
    numeric: numeric
    decimal: numeric
    char: char
    nchar: nchar
    varchar: varchar
    nvarchar: varchar
    nvarchar2: varchar
    varchar2: varchar
    clob: clob
    text: text
    nclob: nclob
    guid: guid
    boolean: boolean
    bool: bool
    blob: blob
    binary: binary
    raw: binary
    rowversion: rowversion
    timestamp: timestamp
    date: date
    datetime: datetime
    time: time
    interval: interval
  gbase8a:
    tinyint: tinyint
    smallint: smallint
    int: int
    bigint: bigint
    float: float
    double: double
    decimal: decimal
    numeric: numeric
    char: char
    varchar: varchar
    text: text
    blob: blob
    longblob: longblob
    date: date
    datetime: datetime
    time: time
    timestamp: timestamp
  cassandra:
    bigint: bigint
    blob: blob
    boolean: boolean
    counter: counter
    date: date
    decimal: decimal
    double: double
    float: float
    inet: inet
    int: int
    smallint: smallint
    text: text
    time: time
    timestamp: timestamp
    datetime: timestamp
    tinyint: tinyint
    uuid: uuid
    varchar: varchar
    varint: varint
    map: map
    set: set
    list: list